name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t tools-archive  .

      - name: test
        run: docker run -v $PWD/data:/data --env ARCHIVE_PATH=/data/inputs tools-archive
